//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Daltons
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Intervention = new HashSet<Intervention>();
        }
    
        public int id_client { get; set; }
        public string nom_client { get; set; }
        public string prenom_client { get; set; }
        public string num_adresse_client { get; set; }
        public string adresse_client { get; set; }
        public string cp_adresse_client { get; set; }
        public string ville_client { get; set; }
        public string tel_mobile_client { get; set; }
        public int id_entity { get; set; }
        public string email_client { get; set; }
        public string civilite_client { get; set; }
    
        public virtual Entity Entity { get; set; }
        public virtual ICollection<Intervention> Intervention { get; set; }
    }
}
