//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Daltons
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compte_rendu
    {
        public Compte_rendu()
        {
            this.Intervention = new HashSet<Intervention>();
        }
    
        public int id_compte_rendu { get; set; }
        public string note { get; set; }
        public int id_technicien { get; set; }
        public Nullable<int> id_societe { get; set; }
    
        public virtual Societe Societe { get; set; }
        public virtual Societe Societe1 { get; set; }
        public virtual Societe Societe2 { get; set; }
        public virtual Technicien Technicien { get; set; }
        public virtual ICollection<Intervention> Intervention { get; set; }
    }
}
