//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Daltons
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etat_intervention
    {
        public Etat_intervention()
        {
            this.Intervention = new HashSet<Intervention>();
        }
    
        public int id_etat { get; set; }
        public string libelle { get; set; }
    
        public virtual Etat_intervention Etat_intervention1 { get; set; }
        public virtual Etat_intervention Etat_intervention2 { get; set; }
        public virtual ICollection<Intervention> Intervention { get; set; }
    }
}
