//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Daltons
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materiel
    {
        public Materiel()
        {
            this.Technicien = new HashSet<Technicien>();
        }
    
        public int id_materiel { get; set; }
        public string num_serie { get; set; }
        public string modele { get; set; }
        public string ip { get; set; }
    
        public virtual ICollection<Technicien> Technicien { get; set; }
    }
}
