//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Daltons
{
    using System;
    using System.Collections.Generic;
    
    public partial class Motif_intervention
    {
        public Motif_intervention()
        {
            this.Intervention = new HashSet<Intervention>();
        }
    
        public int id_motif { get; set; }
        public string libelle { get; set; }
        public double prix_h { get; set; }
    
        public virtual ICollection<Intervention> Intervention { get; set; }
    }
}
