//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Daltons
{
    using System;
    using System.Collections.Generic;
    
    public partial class Societe
    {
        public Societe()
        {
            this.Compte_rendu = new HashSet<Compte_rendu>();
            this.Compte_rendu1 = new HashSet<Compte_rendu>();
            this.Compte_rendu2 = new HashSet<Compte_rendu>();
            this.Intervention = new HashSet<Intervention>();
        }
    
        public int id_societe { get; set; }
        public string nom_societe { get; set; }
        public string adresse_societe { get; set; }
        public string email_societe { get; set; }
        public string ville_societe { get; set; }
        public string cp_societe { get; set; }
        public string tel_societe { get; set; }
    
        public virtual ICollection<Compte_rendu> Compte_rendu { get; set; }
        public virtual ICollection<Compte_rendu> Compte_rendu1 { get; set; }
        public virtual ICollection<Compte_rendu> Compte_rendu2 { get; set; }
        public virtual ICollection<Intervention> Intervention { get; set; }
    }
}
